export interface Product {
  name: string;
  category: string;
  price: number;
  dimensions: string;
  description: string;
  images: string[];
  type?: string;
  weight?: string;
}

export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

const B = "/products1_webp/products1";
const B2 = "/products2";

export const shelves: Product[] = [
  {
    name: "Verse",
    type: "Wall-mounted",
    price: 2500,
    dimensions: "36×14×59 cm",
    weight: "1 kg",
    description: "A harmonious blend of form and function, inspired by the fluidity of poetry. Its sleek, flat surface meets a striking triangular silhouette, creating a dynamic visual rhythm.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Narrative (Big)",
    type: "Free Standing",
    price: 22000,
    dimensions: "72×22×150 cm",
    weight: "14 kg",
    description: "Embodies the intricate journey of storytelling, with a design that blends bold straight lines and graceful curves.",
    images: [`${B}/Narrative-bookshelf1.webp`, `${B}/Narrative-bookshelf2.webp`, `${B}/Narrative-bookshelf3.webp`],
  },
  {
    name: "Narrative (Small)",
    type: "Free Standing",
    price: 14000,
    dimensions: "56×22×106 cm",
    weight: "7 kg",
    description: "Embodies the intricate journey of storytelling, with a design that blends bold straight lines and graceful curves.",
    images: [`${B}/Narrative-bookshelf1.webp`, `${B}/Narrative-bookshelf2.webp`, `${B}/Narrative-bookshelf3.webp`],
  },
  {
    name: "Sonnet",
    type: "Wall-mounted",
    price: 3200,
    dimensions: "14×11×96 cm",
    weight: "1.5 kg",
    description: "A sleek, long bookshelf with a subtle, almost invisible design, creates the illusion of floating books.",
    images: [`${B2}/sonnet-bookshelf.webp`],
  },
  {
    name: "Scroll",
    type: "Wall-mounted",
    price: 3200,
    dimensions: "30×11×96 cm",
    weight: "1.5 kg",
    description: "A sophisticated invisible bookshelf designed to blend functionality with modern elegance. Its long and sleek C-shaped display creates the illusion of floating books.",
    images: [`${B}/scroll-bookshelf1.webp`, `${B}/scroll-bookshelf2.webp`],
  },
  {
    name: "Saga",
    type: "Wall-mounted",
    price: 2500,
    dimensions: "64×11×87 cm",
    weight: "1.5 kg",
    description: "A unique invisible bookshelf crafted to transform your book collection into a dynamic display. Its long diagonal design adds an eye-catching geometric flair.",
    images: [`${B}/Saga-bookshelf1.webp`],
  },
  {
    name: "Index",
    type: "Wall-mounted",
    price: 4000,
    dimensions: "32×14×76 cm",
    weight: "1.5 kg",
    description: "A clever fusion of form and function, featuring a two-way design with invisible folds.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Preface (Big)",
    type: "Free Standing",
    price: 15500,
    dimensions: "30×25×133 cm",
    weight: "10 kg",
    description: "Grid-like sections designed to display books and decorative pieces. A striking, complex bend at the top adds architectural drama.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Preface (Small)",
    type: "Table Top",
    price: 8500,
    dimensions: "21×21×100 cm",
    weight: "5 kg",
    description: "Grid-like sections designed to display books and decorative pieces. A striking, complex bend at the top adds architectural drama.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Prologue",
    type: "Free Standing",
    price: 14000,
    dimensions: "35×25×127 cm",
    weight: "8 kg",
    description: "A bold statement of design, featuring four long, alternating boxes that extend inward and outward.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Chapter",
    type: "Table Top",
    price: 5500,
    dimensions: "44×25×80 cm",
    weight: "4 kg",
    description: "Combines functionality with soft, rounded edges for a modern, inviting look.",
    images: [`${B}/Chapter-bookshelf1.webp`, `${B}/Chapter-bookshelf2.webp`],
  },
  {
    name: "Tale",
    type: "Wall-mounted",
    price: 5500,
    dimensions: "59×11×82 cm",
    weight: "2 kg",
    description: "Features a striking, tapered ladder design with three angled compartments.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Ink (Set of 3)",
    type: "Wall-mounted",
    price: 1500,
    dimensions: "15×10×10 cm",
    weight: "0.5 kg",
    description: "Compact and minimalist design, offering an invisible display for your books.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Drama",
    type: "Free Standing",
    price: 9500,
    dimensions: "108×25×118 cm",
    weight: "5 kg",
    description: "Two inverted ladders joining at the top in a dramatic, floor-mounted structure.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Volume 1",
    type: "Free Standing",
    price: 4200,
    dimensions: "30×30×36 cm",
    weight: "2 kg",
    description: "Stackable cubes with a minimalist design — use alone or layer for a modular display.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Volume 2",
    type: "Free Standing",
    price: 7500,
    dimensions: "30×30×75 cm",
    weight: "4 kg",
    description: "Stackable cubes with a minimalist design — use alone or layer for a modular display.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Fiction",
    type: "Wall-mounted",
    price: 5000,
    dimensions: "24×160×25 cm",
    weight: "3 kg",
    description: "Asymmetric, hanging design, creating a sense of intrigue and movement.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Genre",
    type: "Wall-mounted",
    price: 4000,
    dimensions: "35×9.5×40 cm",
    weight: "2 kg",
    description: "A hanging side holder that's perfect for magazines or books. Its curved top doubles as a compact table.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Quill",
    type: "Wall-mounted",
    price: 2700,
    dimensions: "72×14×20 cm",
    weight: "1 kg",
    description: "Bold triangular center, flanked by wing-like extensions on both sides.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Prose (Set of 2)",
    type: "Wall-mounted",
    price: 2000,
    dimensions: "43×14×9.5 cm",
    weight: "0.7 kg",
    description: "Straightforward and clean design, mirrors the simplicity and flow of a well-crafted prose.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Ballad",
    type: "Wall-mounted",
    price: 8500,
    dimensions: "40×15.5×70 cm",
    weight: "7 kg",
    description: "Four unique shelves that come together in a harmonious display with complex bends and fluid lines.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Epic",
    type: "Wall-mounted",
    price: 5500,
    dimensions: "23×22×70 cm",
    weight: "3 kg",
    description: "Bold double-Z shape, with four spacious compartments.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Stanza",
    type: "Wall-mounted",
    price: 2200,
    dimensions: "25.5×14×52 cm",
    weight: "1 kg",
    description: "Double-sided design that allows for a dynamic display with seamless invisible folds at the ends.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Chronicle",
    type: "Free Standing",
    price: 8500,
    dimensions: "30×30×150 cm",
    weight: "5.5 kg",
    description: "Long, floor-mounted design featuring simple, precise folds.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Binding",
    type: "Free Standing",
    price: 17500,
    dimensions: "62×21×200 cm",
    weight: "10 kg",
    description: "Sleek, modern design with a long pipe that elegantly connects three triangles on opposite sides.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Draft",
    type: "Wall-mounted",
    price: 4500,
    dimensions: "25×20×75 cm",
    weight: "3 kg",
    description: "Bold zig-zag design, symbolizing the creative process in motion.",
    images: [`${B2}/shelf1.webp`],
  },
  {
    name: "Parable",
    type: "Table Top",
    price: 3500,
    dimensions: "71×28×31 cm",
    weight: "2.5 kg",
    description: "Long, tabletop design that offers ample capacity for books. Functional and versatile.",
    images: [`${B2}/shelf1.webp`],
  },
].map((s) => ({ ...s, category: "Shelves" }));

export const vases: Product[] = [
  {
    name: "Luna Vase",
    category: "Vases",
    price: 1500,
    dimensions: "13×10×31 cm",
    weight: "1 kg",
    description: "Modern rectangular frame with a built-in metal vase. Perfect for single stems, dried flowers, or minimal arrangements.",
    images: [`${B}/Lunavase1.webp`, `${B}/Lunavase2.webp`, `${B}/Lunavase3.webp`, `${B}/lunavaseb1.webp`, `${B}/lunavaseb3.webp`],
  },
  {
    name: "Maya Vase",
    category: "Vases",
    price: 1600,
    dimensions: "20×20×24 cm",
    weight: "1 kg",
    description: "A minimalist sculptural vase that doubles as a work of art. Ideal for single stems or delicate arrangements.",
    images: [`${B}/mayavasec1.webp`, `${B}/mayavasec2.webp`, `${B}/mayavased1.webp`, `${B}/mayavased2.webp`],
  },
  {
    name: "Terra Vase",
    category: "Vases",
    price: 1600,
    dimensions: "11×11×30 cm",
    weight: "1 kg",
    description: "Striking hexagonal silhouette with clean, precise lines. A sophisticated statement piece that stands alone or holds botanicals.",
    images: [
      `${B2}/Terra-vase-1.webp`, `${B2}/Terra-vase-2.webp`, `${B2}/Terra-vase3.webp`,
      `${B2}/Terra-vase-peach-1.webp`, `${B2}/Terra-vase-peach2.webp`, `${B2}/Terra-vase-peach3.webp`,
      `${B2}/Terra-vase-silver-1.webp`, `${B2}/Terra-vase-silver-2.webp`, `${B2}/Terra-vase-silver-3.webp`,
    ],
  },
  {
    name: "Cala Vase",
    category: "Vases",
    price: 1300,
    dimensions: "10.5×10.5×20 cm",
    weight: "0.5 kg",
    description: "Flowing form with elegant curved panels and a soft, scalloped rim. A versatile accent for any shelf, desk, or tabletop.",
    images: [
      `${B}/Cala-vase-black1.webp`, `${B}/Cala-vase-black2.webp`, `${B}/Cala-vase-black3.webp`,
      `${B}/Cala-vase-green-1.webp`, `${B}/Cala-vase-green2.webp`, `${B}/Cala-vase-green-3.webp`,
    ],
  },
  {
    name: "Aura Vase (S)",
    category: "Vases",
    price: 1500,
    dimensions: "16×16×15 cm",
    weight: "1 kg",
    description: "Innovative 3-in-1 modular set with playful wavy rims. Use together as a layered centrepiece or separately as individual accents.",
    images: [
      `${B}/Aura-vase-8.webp`,`${B}/Aura-vase-1.webp`, `${B}/Aura-vase-2.webp`, `${B}/Aura-vase-3.webp`, `${B}/Aura-vase-4.webp`,
      `${B}/Aura-vase-5.webp`,
    ],
  },
  {
    name: "Aura Vase (M)",
    category: "Vases",
    price: 1700,
    dimensions: "15×15×22 cm",
    weight: "1 kg",
    description: "Innovative 3-in-1 modular set with playful wavy rims. Use together as a layered centrepiece or separately as individual accents.",
    images: [
      `${B}/Aura-vase-7.webp`,`${B}/Aura-vase-1.webp`, `${B}/Aura-vase-2.webp`, `${B}/Aura-vase-3.webp`, `${B}/Aura-vase-4.webp`,
      `${B}/Aura-vase-5.webp`,
    ],
  },
  {
    name: "Aura Vase (L)",
    category: "Vases",
    price: 1900,
    dimensions: "14×14×30 cm",
    weight: "1.5 kg",
    description: "Innovative 3-in-1 modular set with playful wavy rims. Use together as a layered centrepiece or separately as individual accents.",
    images: [
      `${B}/Aura-vase-6.webp`, `${B}/Aura-vase-1.webp`, `${B}/Aura-vase-2.webp`, `${B}/Aura-vase-3.webp`, `${B}/Aura-vase-4.webp`,
      `${B}/Aura-vase-5.webp`,
    ],
  },
  {
    name: "Aura Vase (Set of 3)",
    category: "Vases",
    price: 4500,
    dimensions: "14×14×30 cm",
    weight: "3.5 kg",
    description: "The complete Aura trio — small, medium, and large — with playful wavy rims. Layer them together as a sculptural centrepiece or scatter them as individual accents.",
    images: [
      `${B}/Aura-vase-1.webp`, `${B}/Aura-vase-2.webp`, `${B}/Aura-vase-3.webp`, `${B}/Aura-vase-4.webp`,
      `${B}/Aura-vase-5.webp`,
    ],
  },
];

export const wineHolders: Product[] = [
  {
    name: "Riva",
    category: "Wine Holders",
    price: 2900,
    dimensions: "41.5×41.5×14 cm",
    weight: "1.5 kg",
    description: "Architectural wave design holding up to 4 bottles. A sculptural countertop centrepiece that transforms wine storage into functional art.",
    images: [`${B}/Riva.webp`, `${B}/Riva2.webp`, `${B}/Riva3.webp`],
  },
  {
    name: "Maison",
    category: "Wine Holders",
    price: 3200,
    dimensions: "40×22×25 cm",
    weight: "2 kg",
    description: "Striking honeycomb structure holding 6 bottles. Contemporary geometric precision meets premium freestanding wine storage.",
    images: [
      `${B}/Maison-wineholder-1..webp`, `${B}/Maison-wine-holder2.webp`, `${B}/Maison-wine-holder3.webp`,
      `${B}/Maison-wine-holder-b1.webp`, `${B}/Maison-wine-holderb3.webp`,
    ],
  },
  {
    name: "Clink",
    category: "Wine Holders",
    price: 3200,
    dimensions: "19×14.5×60 cm",
    weight: "2 kg",
    description: "Sleek vertical wall-mounted rack presenting your collection as a floating display. Modular — install one unit or build an entire wine wall.",
    images: [`${B}/clink1.webp`, `${B}/clink2.webp`, `${B}/clink3.webp`, `${B}/clink4.webp`],
  },
  {
    name: "Opera",
    category: "Wine Holders",
    price: 2800,
    dimensions: "40×14.5×39 cm",
    weight: "1.5 kg",
    description: "Wheel-shaped design with artistic cut-outs holding 6 bottles. A dramatic countertop centrepiece inspired by grand performance.",
    images: [`${B}/Opera1-wine-holder-1.webp`, `${B}/Opera-wine-holder-2.webp`, `${B}/Opera-wine-holder-3.webp`],
  },
];

export const organisers: Product[] = [
  {
    name: "Linea Organiser",
    category: "Organisers",
    price: 2100,
    dimensions: "15.5×10×45 cm",
    weight: "1 kg",
    description: "Minimalist tabletop organiser with a stunning continuous silhouette. Ideal as a vanity tray, desk accessory, or countertop shelf.",
    images: [
      `${B}/Linea-organiser-green.webp`, `${B}/Linea%20organiser-green2.webp`,
      `${B}/Linea%20organiser%20light%20green%20.webp`,
    ],
  },
  {
    name: "Perch Organiser",
    category: "Organisers",
    price: 8000,
    dimensions: "73×15×40 cm",
    weight: "7 kg",
    description: "Multi-faceted organiser with staggered compartments. Works freestanding or wall-mounted — perfect for mugs, perfumes, or collectibles.",
    images: [`${B}/Perch-wineholder1.webp`, `${B}/Perchwineholder2.webp`, `${B}/Perchwineholder3.webp`],
  },
  {
    name: "Nest Organiser",
    category: "Organisers",
    price: 4500,
    dimensions: "61×13×61 cm",
    weight: "3 kg",
    description: "Clean geometric grid with unique nesting cradles. A versatile display for coffee mugs, perfumes, or small decorative pieces.",
    images: [`${B}/Nest-wineholder1.webp`, `${B}/Nestwineholder2.webp`, `${B}/Nestwineholder3.webp`, `${B}/Nest-black1.webp`, `${B}/Nestblack2.webp`],
  },
];

export const shoeRacks: Product[] = [
  {
    name: "Step",
    category: "Shoe Display Racks",
    price: 900,
    dimensions: "28×10×24 cm",
    weight: "0.5 kg",
    description: "Wall-mounted cantilevered shelves presenting each shoe as a gallery object. Fully modular — arrange units into any creative configuration.",
    images: [`${B2}/step-shoerack1.webp`, `${B2}/step-shoerack2.webp`, `${B2}/stepshoerack3.webp`, `${B2}/stepshoerackb2.webp`],
  },
  {
    name: "Vault",
    category: "Shoe Display Racks",
    price: 6500,
    dimensions: "31×27×61 cm",
    weight: "6 kg",
    description: "Space-saving design with a hidden front profile. Wall-mounted or freestanding, with customisable layers of 4, 6, or 8.",
    images: [`${B2}/Vaultshoerack1.webp`, `${B2}/Vaultshoerack2.webp`, `${B2}/vaultshoerack3.webp`],
  },
  {
    name: "Orbit",
    category: "Shoe Display Racks",
    price: 5500,
    dimensions: "44×37.5×84 cm",
    weight: "4 kg",
    description: "Circular pods create a gallery-style wall showcase for your collection. Turns any wall into a striking piece of contemporary design.",
    images: [`${B}/Orbit-shoerack1.webp`, `${B}/Orbitshoerack2.webp`, `${B}/Orbitshoerack3.webp`],
  },
  {
    name: "Align",
    category: "Shoe Display Racks",
    price: 3600,
    dimensions: "82.5×26×271 cm",
    weight: "3.5 kg",
    description: "A continuous zig-zag form forged from a single piece of premium aluminium. Bold graphic wall art that doubles as a sophisticated shoe display.",
    images: [`${B}/Alignshoerack.webp`, `${B}/Alignshoerack2.webp`, `${B}/alignshoerack3.webp`],
  },
  {
    name: "Penta",
    category: "Shoe Display Racks",
    price: 3800,
    dimensions: "106.5×26×33 cm",
    weight: "3 kg",
    description: "Uniquely versatile floating wall shelf with five planes — holds shoes, books, small plants, and décor. A dynamic all-in-one display solution.",
    images: [`${B}/pentashoerack.webp`, `${B}/pentashoerack2.webp`],
  },
];
